# Generated by Django 5.2.7 on 2025-11-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('orgánico', 'Orgánico'), ('reciclable', 'Reciclable'), ('no_reciclable', 'No reciclable')], max_length=20)),
                ('categoria_reciclable', models.CharField(blank=True, choices=[('carton', 'Cartón'), ('botellas', 'Botellas'), ('papel', 'Papel'), ('plastico', 'Plástico'), ('metal', 'Metal'), ('vidrio', 'Vidrio')], max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
