# Generated by Django 5.2.7 on 2025-11-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoreciclaje',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoreciclaje',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
